### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by LeoleUCAB** [LeoleUCAB/python-caiman#1]
- [ ] Agregar la base de datos
- [ ] Crear el parseador de documentos
- [ ] Crear el generador de reportes
- [ ] Separar cada cosa en su modulo
- [ ] Condiciones en caso de que el archivo parseado tenga algun error o un string inesperado
- [ ] Agregar informacion relevante al README
- [ ] Crear menu inicial, no es necesario interfaz, pero un menu ASCII basico para seleccionar opciones es requerido
